// Auto-generated by lstranspile.h from C:\Users\daeli\Documents\DispersedEngine\projects\OpenWorld\scripts\game.lh — do not hand-edit; edit the .lh source instead.
// Auto-generated from C:\Users\daeli\Documents\DispersedEngine\projects\OpenWorld\scripts\game.h
// Auto-generated by lstranspile.h from C:\Users\daeli\Documents\DispersedEngine\projects\OpenWorld\scripts\game.lh — do not hand-edit; edit the .lh source instead.
// Auto-generated from C:\Users\daeli\Documents\DispersedEngine\projects\OpenWorld\scripts\game.h
// Auto-generated by lstranspile.h from C:\Users\daeli\Documents\DispersedEngine\projects\OpenWorld\scripts\game.lh — do not hand-edit; edit the .lh source instead.
// Auto-generated from C:\Users\daeli\Documents\DispersedEngine\projects\OpenWorld\scripts\game.h
// Auto-generated by lstranspile.h from C:\Users\daeli\Documents\DispersedEngine\projects\OpenWorld\scripts\game.lh — do not hand-edit; edit the .lh source instead.
// Auto-generated from C:\Users\daeli\Documents\DispersedEngine\projects\OpenWorld\scripts\game.h
#pragma once
#include "engine.h"
#include "particles.h"

constexpr float healthbarOffsetY = -30.0f;



constexpr float waterbarOffsetY = -60.0f;



constexpr float foodbarOffsetY = -90.0f;



constexpr SDL_FRect barIconsrcRect = {0,0,26,26};



constexpr float barOffsetX = -30.0f;



constexpr float WaterNFoodMaxValue = 200.0f;



constexpr float WaterNFoodBarHeight = 12.0f;



constexpr float WaterNFoodBarWidth = 100.0f;




struct GameContext {
    SDL_Renderer*       renderer        = nullptr;



    TTF_TextEngine*     textEngine      = nullptr;



    SDL_Window*         window          = nullptr;



    Scene*              scene           = nullptr;



    Tools::Camera       camera;



    SDL_Gamepad*        gamepad         = nullptr;



    Physics::PhysicsWorld* physicsWorld = nullptr;


  
    SceneParser*        sceneParser     = nullptr;


   
    std::string         sceneFilePath;


   
    float gamepadCursorX = 0.0f;



    float gamepadCursorY = 0.0f;



    bool confirmDownLastFrame = false;


  
    SDL_Texture* healthbarIcon;



    SDL_Texture* waterbarIcon;



    SDL_Texture* foodbarIcon;



};





struct Biome {
    std::string textureName;



    int gridX = 0;



    int gridY = 0;



    int id = 0;



};




class WaterBar {
public:
    WaterBar(float max = 100.0f, float width = 100.0f, float height = 12.0f);



    // Virtual destructor ensures proper cleanup of derived classes
    virtual~ WaterBar() = default;


 
    void damage(float amount);



    void heal(float amount);



    float getCurrentVal() const;



    float getPercentage() const;



    virtual void render(SDL_Renderer* renderer, float screenX, float screenY);




protected:
    float maxValue, currentValue;



    float barWidth, barHeight;



};




class FoodBar : public WaterBar {
    public:
        using WaterBar::WaterBar;


 // inherits constructor
        // virtual destructor is already used behind the scenes
        // render method is overrided
        void render(SDL_Renderer* renderer, float screenX, float screenY) override;



};




// Forward declaration for MathDialog (defined in game.cpp)
class MathDialog;




class GameScript : public ScriptBase {
public:
    std::string getName() const override { return "GameScript";


 };
    GameContext* ctx = nullptr;




    // engine.h's ScriptRegistry/SceneParser/change_scene machinery only
    // knows ScriptBase, not GameContext (a project-defined type), so the
    // context is handed over as void* and cast back here. Called once
    // right after ScriptRegistry creates this instance for a scene, and
    // again by change_scene() whenever this script becomes the active one
    // for a newly-loaded scene.
    void setContext(void* context) override { ctx = static_cast<GameContext*>(context);


 };

    float normalSpeed = 300.0f;


   // your default speed
    float moveSpeed = 300.0f;



    float slowSpeed = 150.0f;




    int puddleContactCount = 0;



    bool isInPuddle = false;






    void handleSensorTouch(b2ShapeId sensorShape, b2ShapeId visitorShape, bool isBegin);




    // Biome grid configuration
    std::vector<Biome> biomes;



    int biomeGridW = 3;



    int biomeGridH = 5;



    int biomeTileCountX = 5;



    int biomeTileCountY = 5;




    // Water
    WaterBar waterbar;



    float waterDepletionRate = 0.3f;


        // units per second
    bool isDrinking = false;



    float drinkTimer = 0.0f;



    float drinkDuration = 2.0f;


             // seconds

    // Food
    FoodBar foodbar;



    float foodDepletionRate = 0.1f;



    bool isEating = false;



    float eatTimer = 0.0f;



    float eatDuration = 2.0f;






    bool movementLocked = false;


            // blocks player input

    // Math dialog
    std::unique_ptr<MathDialog> mathDialog;



    bool isMathDialogActive = false;




    // Methods
    void showMathDialog();



    void onMathAnswer(bool correct);




    void startDrinking();



    void finishDrinking();




    void startEating();



    void finishEating();




    Entity lastHitEntity = (Entity)-1;



    float hitCooldown = 0.0f;




    Tools::Healthbar healthbar;




    // Drives the black-particle "vanish" effect (see particles.h). Started
    // once when the player dies (see checkCollisions), ticked every frame
    // from onUpdate(), and drawn from onDraw(). A vanish's own progress and
    // particles live entirely inside this object, so nothing else on
    // GameScript needs to track fade state by hand.
    Particles::VanishSystem vanishEffects;




    void checkCollisions(float dt);



    
    float knockbackTimer = 0.0f;



    float knockbackSpeed = 500.0f;



    bool deathState = false;




    // Engine APIs
    Tools::BackgroundMap bgMap;



    Tools::Minimap minimap;




    bool drawPhysicsDebug = false;




    // --- Y-Sorting ---
    bool ySortEnabled = true;




    // Which point of each entity's rect is used for depth sorting.
    // Bottom = feet-based sorting (recommended for top-down games with
    // mixed-height entities like a tall player and short grass).
    Tools::YSortAnchor ySortAnchor = Tools::YSortAnchor::Bottom;




    Entity flower = (Entity)-1;



    Entity grass  = (Entity)-1;



    Entity catcus = (Entity)-1;



    Entity emptyTree = (Entity)-1;



    Entity iceCrystal = (Entity)-1;



    Entity snowyEmptyTree = (Entity)-1;



    Entity fruitTree = (Entity)-1;



    Entity puddle = (Entity)-1;




    std::vector<Entity> decorationEntities;



    std::vector<Entity> importantEntities;




    // Controls whether the one-time biome/decoration generation guard
    // (Scene::areBiomesAndEntitiesGenerated) is honored:
    //   true  -> once biomes/decorations are generated for a scene, later
    //            onStart() calls (e.g. after a reload) skip generation.
    //   false -> ignore the saved flag and always (re)generate biomes and
    //            decoration entities on every onStart(), useful for
    //            iterating on generation logic during development.
    bool shouldStopRegeneration = true;




    void buildBiomeGrid();



    void rebuildBgMap();



    void spawnRandomDecorations();



    void checkContacts(float dt);



    float puddleCooldown = 0.0f;


   // prevents multiple triggers per frame

    Entity player = (Entity)-1;



    Entity background = (Entity)-1;




    void onStart() override;



    void onUpdate(float dt) override;



    void onDraw() override;



    void onEnd() override;



    void onEvent(const SDL_Event& e) override;




private:
    float elapsed = 0.0f;



};